/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ObsImport } from './routes/obs'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const ObsRoute = ObsImport.update({
  id: '/obs',
  path: '/obs',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/obs': {
      id: '/obs'
      path: '/obs'
      fullPath: '/obs'
      preLoaderRoute: typeof ObsImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/obs': typeof ObsRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/obs': typeof ObsRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/obs': typeof ObsRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/obs'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/obs'
  id: '__root__' | '/' | '/obs'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ObsRoute: typeof ObsRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ObsRoute: ObsRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/obs"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/obs": {
      "filePath": "obs.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
