name: test-workflow

on:
  workflow_dispatch:
    inputs:
      first_name:
        description: "Your first name"
        required: true
        default: ""
        type: string
      last_name:
        description: "Your last name"
        required: true
        default: ""
        type: string
      confirm:
        type: boolean
        default: false
        required: true
      country:
        type: string
        default: France
        required: true
      branch:
        type: string
        required: true
        default: ""

jobs:
  print:
    runs-on: ubuntu-24.04
    steps:
      - name: Print everything
        run: |
          echo "First name => ${{inputs.first_name}}"
          echo "Last name => ${{inputs.last_name}}"
          echo "Branch => ${{inputs.branch}}"
          echo "Country => ${{inputs.country}}"
          echo "Is confirmed? => ${{inputs.confirm}}
