name: test-workflow

on:
  workflow_dispatch:
    inputs:
      first_name:
        description: "Your first name"
        required: true
        default: ""
        type: string
      last_name:
        description: "Your last name"
        required: true
        default: ""
        type: string
      is_minor:
        type: boolean
        default: true
        required: true
      branch:
        type: string
        required: true
        default: ""

jobs:
  print:
    runs-on: ubuntu-24.04
    steps:
      - name: Print everything
        run: |
          echo "First name => ${{inputs.first_name}}"
          echo "Last name => ${{inputs.last_name}}"
          echo "Branch => ${{inputs.branch}}"
